### ISSUE TITLE
ability to claim from pool - backend

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/payment-backend#4]
# Bounty

When a rightsholder clicks a title on its dashboard, a breakdown of revenues by region is shown. next to each region there is a payout button. When the rightsholder clicks the payout button a request is sent to backend, which will then construct a transaction and send funds from the collection pool to the address of the rightsholder. 

## Scope

- api endpoint to take payout requests: `POST /pool/claim/<movieId>/<region>/`
  - error handling
    - 404 - no address for rightsholder found
    - 400 - not admin of collection pool
    - 400 - nothing to distribute
    - 400 - invalid movieId or not found in contract
    - 500 - out of gas
- calculation of revenue (get `all collected - all distributed - all refunded` in subgraph)
- transaction construction and sending
- to prevent double-claims a similar infrastructure like for token faucet should be used:

```
                     +-----------+                           +-----------+
                     |subgraph   |                           |subgraph   |
                     +--+--------+                           +--+--------+
                        |                                          ^
                        +                                          |
+------------+      +---+-----+      +----+    +-----------+    +-------+    +-----+
|API gateway +----> |receiver +----->+SQS +--> |sender     +--->+ pool  +--->+ RH  |
+------------+      |lambda   |      +----+    |lambda     |    +-------+    +-----+
                    +-----+---+                |(singleton)|
                          ^                    +-+---------+
                          |    +---+             ^
                          +----+DB +<------------+
                               +---+
```

## Deliverables

- code + tests
- deployed API + funded key

## Funding Circle
WR

## Bounty Owner/Gardener
@johannbarbie as RepLink

## Roles
bounty gardener: @johannbarbie  / 40 DAI
bounty worker: @troggy  / 420 DAI
bounty reviewer: @johannbarbie  / 90 DAI

**Comment by troggy** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/163447/85010271-66584f00-b168-11ea-9ba0-f01613ead26a.png">

**Comment by troggy** [comment]
@johannbarbie Collection Pool should be owned by the account of the payment backend/faucet. What was your plan? Change owner?

**Comment by johannbarbie** [comment]
> @johannbarbie Collection Pool should be owned by the account of the payment backend/faucet. What was your plan? Change owner?

yes, a hot private key on the backend, until we replace it with merkle proofs on chain in a later version.

**Comment by johannbarbie** [comment]
transferred ownership of Collection Pool to faucet address: https://blockscout.com/poa/xdai/tx/0x72b089073185875e20d327ba0560d20987a990e9269f9e25cc6712a20e02b940/internal_transactions
